server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:h2:mem:kshop-member
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #                show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: /doc/swagger
    operations-sorter: method

jwt:
  secret: HELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLD
